# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ausbildung Brandenburg
email: your-email@vodafone.de
description: Ausbildungszentrum Brandenburg, Qualifizierte Aus- und Weiterbildung für Sicherheitsfachleute. Ausbildung zur geprüften IHK Sicherheitskraft, Sachkundeprüfung im Wach- und Sicherheitsgewerbe und Ausbildung im Waffenrecht und Waffensachkunde.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ausbildung-brandenburg.de/" # the base hostname & protocol for your site

sass:
  sass_dir: _sass
include: ['_pages']

# Build settings
markdown: kramdown
